source 'http://rubygems.org'

gem 'sinatra'
gem 'nokogiri'
gem 'tempodb'
gem 'rerun'
gem 'haml'
gem 'statsample'
gem 'gon-sinatra'
gem 'sinatra-asset-pipeline'
gem 'shotgun'
gem 'yahoofinance'
gem 'omniauth-github'
gem 'sinatra-session'
gem 'sinatra-support'
gem 'mongo'
gem 'bson_ext'
#gem 'talib_ruby'
