class Asset

  SANTANDER_FUNDS_MARKET_INDEX = 'SANTANDER INDEX'
  MERVAL_MARKET_INDEX = '%5EMERV'

  def self.santander_fund_symbols
    ['SUPER AHORRO $', 'SUPER AHORRO PLUS A', 'SUPERGESTION MIX VI A', 'SUPERFONDO RENTA $', 'SUPER BONOS INTERNACIONAL C',
    'SUPERFONDO DOL PLUS C REEX EN PESOS', 'SUP RTA LATINOAMERICA C REEX EN PESOS', 'SUPERGESTION INTERNACIONAL C', 'SUPERFONDO ACCIONES',
    'SUPERFONDO RENTA VARIABLE', 'SUPERFONDO ACCS BRASIL REEX EN PESOS C', 'SUP LATINOAMERICA REEXPRESADO EN PESOS', 'SUPER RENTA FUTURA A']
  end

  def self.merval_stock_symbols
    %w{ALUA.BA APBR.BA BHIP.BA BMA.BA CEPU2.BA COME.BA CRES.BA EDN.BA ERAR.BA FRAN.BA GGAL.BA INDU.BA IRSA.BA LEDE.BA MIRG.BA MOLI.BA PAMP.BA PESA.BA STD.BA TECO2.BA TEF.BA TGNO4.BA TRAN.BA TS.BA YPFD.BA}
  end

  def self.merval_stock_symbols_with_index
    merval_stock_symbols << MERVAL_MARKET_INDEX
  end

  def self.all_symbols
    santander_fund_symbols.concat merval_stock_symbols
  end

  def self.all_indexes
    [SANTANDER_FUNDS_MARKET_INDEX, MERVAL_MARKET_INDEX]
  end
end